#!/bin/bash
set -euo pipefail

NAMESPACE="${NAMESPACE:-default}"
RESOURCE="${RESOURCE:-svc/node-dependency-matrix}"
LOCAL_HTTP_PORT="${LOCAL_HTTP_PORT:-8080}"
REMOTE_HTTP_PORT="${REMOTE_HTTP_PORT:-8080}"
LOCAL_GRPC_PORT="${LOCAL_GRPC_PORT:-9090}"
REMOTE_GRPC_PORT="${REMOTE_GRPC_PORT:-9090}"

kubectl -n "${NAMESPACE}" port-forward "${RESOURCE}" \
  "${LOCAL_HTTP_PORT}:${REMOTE_HTTP_PORT}" \
  "${LOCAL_GRPC_PORT}:${REMOTE_GRPC_PORT}"
