version: '3.8'

services:
  app:
    build: .
    container_name: nodesqlapp
    restart: always
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASSWORD=MYSQL_PASSWORD
      - MYSQL_DATABASE=sample_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"  # Change this line
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
